[Variables]
;============================================= General

BPM          =120
Reflect      =70
Scale        =1
; Recommended: 0.5 - 1 (Any value works)

PlayType     =0
;0=Dance, 1=Dance with Plugin, 2=Dance with Audio

SetAnimation =1
Hide         =0
Mirror	     =0

;============================================= Plugin

Plugin       =WebNowPlaying
; NowPlaying,  Web,  GPDMP

Player       =AIMP
; AIMP,  iTunes (10.2),  Winamp,  WMP,  CAD (Foobar & Musicbee)
; Only applicable if using the NowPlaying plugin

;============================================= Audio

Threshold=0.01
PeakDecay=300
;Decay in ms

;============================================= Animations

Animation0=Waiting
Animation1=Stepping
Animation2=Jumping
Animation3=Zombie
Animation4=Waving
Animation5=Hula
Animation6=Windmill
Animation7=Zitabata
Animation8=Dervish

;============================================= System Variables (No touch)

UpdateRate =125
Random=0
